{% set name = "useq-schema" %}
{% set version = "0.4.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/useq_schema-{{ version }}.tar.gz
  sha256: c82b3eae900ff509374a642525850fc774ad120a6df17febfa33605eb73b5919

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - hatchling
    - hatch-vcs
  run:
    - numpy
    - pydantic >=1.7
    - pydantic-compat >=0.0.1
    - python >=3.8
    - typing-extensions

test:
  imports:
    - useq
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/useq-schema
  summary: Schema for multi-dimensional microscopy experiments
  dev_url: https://github.com/tlambert03/useq-schema
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - tlambert03
