{% set name = "useq-schema" %}
{% set version = "0.4.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/useq_schema-{{ version }}.tar.gz
  sha256: 9616a33636e8f4f0f87cb2fca23aa9e028fa976e3e90c3dc7a5cb2867c68cdd7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - hatchling
    - hatch-vcs
  run:
    - numpy
    - pydantic >=1.7
    - pydantic-compat >=0.0.1
    - python >=3.8
    - typing-extensions

test:
  imports:
    - useq
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/useq-schema
  summary: Schema for multi-dimensional microscopy experiments
  dev_url: https://github.com/tlambert03/useq-schema
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - tlambert03
