{% set name = "useq-schema" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/useq_schema-{{ version }}.tar.gz
  sha256: ac88b151dbca589f22b8e614ce9ffc8cb7d7af366b1c15ee527649b7d706c04e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - hatchling
    - hatch-vcs
  run:
    - numpy
    - pydantic <2.0
    - python >=3.7
    - typing-extensions

test:
  imports:
    - useq
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tlambert03/useq-schema
  summary: Schema for multi-dimensional microscopy experiments
  dev_url: https://github.com/tlambert03/useq-schema
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - tlambert03
