{% set name = "useq-schema" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/useq-schema-{{ version }}.tar.gz
  sha256: cc8f2e30c58eaa52626ca0d527450b30fec1e2e116057ae4cbda27758451629d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - numpy
    - pydantic
    - python >=3.7

test:
  imports:
    - useq
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tlambert03/useq-schema
  summary: Schema for multi-dimensional microscopy experiments
  dev_url: https://github.com/tlambert03/useq-schema
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - tlambert03
