{% set name = "useq-schema" %}
{% set version = "0.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/useq_schema-{{ version }}.tar.gz
  sha256: e61b6d2f88f80f6b52b28f9defffc5f082fe04c69883396a864c4323aa85067b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
  run:
    - numpy
    - pydantic >=2.6
    - python >={{ python_min }}
    - typing-extensions

test:
  imports:
    - useq
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/useq-schema
  summary: Schema for multi-dimensional microscopy experiments
  dev_url: https://github.com/tlambert03/useq-schema
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - tlambert03
